// Browser-side PDF report. Opens a print-ready HTML window styled for PDF
// export — works offline. In production a Cloud Function generates the same
// report server-side using @react-pdf/renderer (see functions/src/index.ts).
import type { Inspection } from '@/types';

export function generatePdf(ins: Inspection) {
  const grouped = ins.items.reduce<Record<string, typeof ins.items>>((a, it) => { (a[it.category] ||= []).push(it); return a; }, {});
  const fails = ins.items.filter(i => i.status === 'fail');
  const passes = ins.items.filter(i => i.status === 'pass').length;

  const html = `<!doctype html>
<html><head><meta charset="utf-8"><title>InspectFlow Report — ${escape(ins.unitLabel)} · ${escape(ins.propertyName)}</title>
<style>
  @page { size: letter; margin: 0.6in; }
  body { font-family: 'JetBrains Mono', ui-monospace, monospace; color: #111; }
  h1 { font-size: 28px; letter-spacing: -1px; margin: 0 0 4px; }
  h2 { font-size: 14px; text-transform: uppercase; letter-spacing: 2px; border-bottom: 3px solid #111; padding-bottom: 4px; margin: 24px 0 8px; }
  .eyebrow { font-size: 10px; text-transform: uppercase; letter-spacing: 3px; color: #666; }
  .card { border: 3px solid #111; padding: 12px 16px; margin: 12px 0; }
  .grid { display: grid; grid-template-columns: repeat(4, 1fr); gap: 8px; margin: 12px 0; }
  .tile { border: 3px solid #111; padding: 8px 12px; }
  .tile .n { font-size: 28px; font-weight: 800; }
  .item { display: flex; justify-content: space-between; gap: 12px; padding: 8px 0; border-bottom: 1px solid #ccc; font-size: 11px; }
  .tag { display: inline-block; padding: 1px 6px; border: 2px solid #111; font-size: 10px; text-transform: uppercase; letter-spacing: 1px; }
  .pass { background: #b6e8c1; }
  .fail { background: #f3a5a5; }
  .pending { background: #eee; }
  .na { background: #111; color: #fff; }
  .summary { background: #fff5e0; border: 3px solid #111; padding: 16px; }
  footer { margin-top: 24px; font-size: 9px; color: #888; text-align: center; }
</style></head>
<body>
  <div class="eyebrow">// inspectflow report</div>
  <h1>${escape(ins.unitLabel)} — ${escape(ins.propertyName)}</h1>
  <div class="eyebrow">${escape(ins.status.replace('_', ' '))} · inspector ${escape(ins.inspectorName)} · scheduled ${new Date(ins.scheduledFor).toLocaleString()}${ins.completedAt ? ' · completed ' + new Date(ins.completedAt).toLocaleString() : ''}</div>

  <div class="grid">
    <div class="tile"><div class="eyebrow">Pass</div><div class="n">${passes}</div></div>
    <div class="tile"><div class="eyebrow">Fail</div><div class="n">${fails.length}</div></div>
    <div class="tile"><div class="eyebrow">Pending</div><div class="n">${ins.items.filter(i => i.status === 'pending').length}</div></div>
    <div class="tile"><div class="eyebrow">Total</div><div class="n">${ins.items.length}</div></div>
  </div>

  ${ins.aiSummary ? `<h2>AI condition summary</h2><div class="summary">${escape(ins.aiSummary)}</div>` : ''}

  ${ins.generalNotes ? `<h2>Inspector notes</h2><div class="card">${escape(ins.generalNotes)}</div>` : ''}

  <h2>Checklist</h2>
  ${Object.entries(grouped).map(([cat, items]) => `
    <div class="card">
      <div class="eyebrow">${escape(cat)}</div>
      ${items.map(it => `
        <div class="item">
          <div>${escape(it.label)}${it.notes ? `<div style="font-size:10px;color:#555;margin-top:2px">${escape(it.notes)}</div>` : ''}</div>
          <div><span class="tag ${it.status}">${it.status === 'na' ? 'N/A' : it.status}</span>${it.ticketCreated ? ' <span class="tag" style="background:#ff9933">ticket</span>' : ''}</div>
        </div>
      `).join('')}
    </div>
  `).join('')}

  <footer>Generated by INSPECT/FLOW · ${new Date().toLocaleString()}</footer>
  <script>window.onload = () => setTimeout(() => window.print(), 250);</script>
</body></html>`;

  const w = window.open('', '_blank');
  if (!w) return;
  w.document.write(html);
  w.document.close();
}

function escape(s: string | undefined | null): string {
  if (s == null) return '';
  return String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c] as string));
}
