import type { Property, Unit, Inspection, Ticket, UserDoc, InspectionItem } from '@/types';

const NOW = Date.now();
const DAY = 24 * 60 * 60 * 1000;

export const SEED_USERS: UserDoc[] = [
  { uid: 'u_admin', email: 'admin@inspectflow.demo', name: 'Dana Hill', role: 'admin', createdAt: NOW - 30 * DAY },
  { uid: 'u_insp_1', email: 'marco@inspectflow.demo', name: 'Marco Reyes', role: 'inspector', createdAt: NOW - 25 * DAY },
  { uid: 'u_insp_2', email: 'priya@inspectflow.demo', name: 'Priya Shah', role: 'inspector', createdAt: NOW - 20 * DAY },
  { uid: 'u_mgr_1', email: 'jordan@inspectflow.demo', name: 'Jordan Park', role: 'manager', createdAt: NOW - 28 * DAY },
];

export const SEED_PROPERTIES: Property[] = [
  {
    id: 'p_oakcrest',
    name: 'Oakcrest Apartments',
    address: '418 Oak Crest Dr',
    city: 'Austin', state: 'TX', zip: '78704',
    type: 'residential',
    yearBuilt: 1998,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1568605114967-8130f3a36994?w=800&q=70',
    unitCount: 12,
    createdAt: NOW - 200 * DAY,
  },
  {
    id: 'p_lawson',
    name: 'Lawson Lofts',
    address: '212 E 6th St',
    city: 'Austin', state: 'TX', zip: '78701',
    type: 'residential',
    yearBuilt: 2014,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1545324418-cc1a3fa10c00?w=800&q=70',
    unitCount: 8,
    createdAt: NOW - 150 * DAY,
  },
  {
    id: 'p_riverside',
    name: 'Riverside Townhomes',
    address: '900 Riverside Dr',
    city: 'Austin', state: 'TX', zip: '78741',
    type: 'residential',
    yearBuilt: 2006,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1570129477492-45c003edd2be?w=800&q=70',
    unitCount: 6,
    createdAt: NOW - 110 * DAY,
  },
  {
    id: 'p_warehouse',
    name: 'Westside Industrial Park',
    address: '4500 Industrial Blvd',
    city: 'Austin', state: 'TX', zip: '78745',
    type: 'commercial',
    yearBuilt: 1989,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1586528116311-ad8dd3c8310d?w=800&q=70',
    unitCount: 4,
    createdAt: NOW - 90 * DAY,
  },
  {
    id: 'p_cedarpark',
    name: 'Cedar Park Cottages',
    address: '1840 Cedar Bend',
    city: 'Cedar Park', state: 'TX', zip: '78613',
    type: 'residential',
    yearBuilt: 2018,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1554995207-c18c203602cb?w=800&q=70',
    unitCount: 10,
    createdAt: NOW - 220 * DAY,
  },
  {
    id: 'p_mockingbird',
    name: 'Mockingbird Manor',
    address: '7203 N Lamar Blvd',
    city: 'Austin', state: 'TX', zip: '78752',
    type: 'residential',
    yearBuilt: 2002,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1502672260266-1c1ef2d93688?w=800&q=70',
    unitCount: 24,
    createdAt: NOW - 175 * DAY,
  },
  {
    id: 'p_travisheights',
    name: 'Travis Heights Bungalows',
    address: '1612 Newning Ave',
    city: 'Austin', state: 'TX', zip: '78704',
    type: 'residential',
    yearBuilt: 1976,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1542621334-a254cf47733d?w=800&q=70',
    unitCount: 4,
    createdAt: NOW - 130 * DAY,
  },
  {
    id: 'p_eastside',
    name: 'Eastside Brownstones',
    address: '2510 E 12th St',
    city: 'Austin', state: 'TX', zip: '78702',
    type: 'residential',
    yearBuilt: 2010,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1494526585095-c41746248156?w=800&q=70',
    unitCount: 16,
    createdAt: NOW - 105 * DAY,
  },
  {
    id: 'p_mueller',
    name: 'Mueller Mid-Rise',
    address: '4550 Mueller Blvd',
    city: 'Austin', state: 'TX', zip: '78723',
    type: 'residential',
    yearBuilt: 2019,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1600596542815-ffad4c1539a9?w=800&q=70',
    unitCount: 32,
    createdAt: NOW - 75 * DAY,
  },
  {
    id: 'p_hillcrest',
    name: 'Hillcrest Garden Apartments',
    address: '8420 Burnet Rd',
    city: 'Austin', state: 'TX', zip: '78757',
    type: 'residential',
    yearBuilt: 1985,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1564013799919-ab600027ffc6?w=800&q=70',
    unitCount: 18,
    createdAt: NOW - 60 * DAY,
  },
  {
    id: 'p_northgate',
    name: 'Northgate Office Plaza',
    address: '11410 Jollyville Rd',
    city: 'Austin', state: 'TX', zip: '78759',
    type: 'commercial',
    yearBuilt: 2001,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1497366216548-37526070297c?w=800&q=70',
    unitCount: 6,
    createdAt: NOW - 45 * DAY,
  },
  {
    id: 'p_bouldin',
    name: 'Bouldin Creek Live-Work Lofts',
    address: '1604 S 1st St',
    city: 'Austin', state: 'TX', zip: '78704',
    type: 'commercial',
    yearBuilt: 2015,
    managerId: 'u_mgr_1', managerName: 'Jordan Park',
    photoUrl: 'https://images.unsplash.com/photo-1497366811353-6870744d04b2?w=800&q=70',
    unitCount: 8,
    createdAt: NOW - 30 * DAY,
  },
];

export const SEED_UNITS: Unit[] = [
  // Oakcrest
  { id: 'u_oc_2b', propertyId: 'p_oakcrest', label: 'Unit 2B', bedrooms: 2, bathrooms: 1, sqft: 850, tenant: 'Henry Liu', createdAt: NOW - 200 * DAY },
  { id: 'u_oc_3a', propertyId: 'p_oakcrest', label: 'Unit 3A', bedrooms: 1, bathrooms: 1, sqft: 620, tenant: 'Sasha Volkov', createdAt: NOW - 200 * DAY },
  { id: 'u_oc_4c', propertyId: 'p_oakcrest', label: 'Unit 4C', bedrooms: 3, bathrooms: 2, sqft: 1100, tenant: 'Yuki Tanaka', createdAt: NOW - 200 * DAY },
  // Lawson
  { id: 'u_law_201', propertyId: 'p_lawson', label: 'Loft 201', bedrooms: 1, bathrooms: 1, sqft: 720, tenant: 'Cam Rivera', createdAt: NOW - 150 * DAY },
  { id: 'u_law_305', propertyId: 'p_lawson', label: 'Loft 305', bedrooms: 2, bathrooms: 2, sqft: 1050, tenant: 'Avery Stone', createdAt: NOW - 150 * DAY },
  // Riverside
  { id: 'u_rs_a1', propertyId: 'p_riverside', label: 'Townhome A1', bedrooms: 3, bathrooms: 2, sqft: 1400, tenant: 'The Patel Family', createdAt: NOW - 110 * DAY },
  { id: 'u_rs_b2', propertyId: 'p_riverside', label: 'Townhome B2', bedrooms: 3, bathrooms: 2, sqft: 1400, tenant: 'The Okonkwo Family', createdAt: NOW - 110 * DAY },
  // Warehouse
  { id: 'u_wh_a', propertyId: 'p_warehouse', label: 'Bay A', sqft: 4200, tenant: 'Hilltop Logistics', createdAt: NOW - 90 * DAY },
  { id: 'u_wh_b', propertyId: 'p_warehouse', label: 'Bay B', sqft: 4200, tenant: 'Vector Auto Body', createdAt: NOW - 90 * DAY },
  // Cedar Park Cottages
  { id: 'u_cp_3', propertyId: 'p_cedarpark', label: 'Cottage 3', bedrooms: 2, bathrooms: 2, sqft: 980, tenant: 'The Reyes Family', createdAt: NOW - 220 * DAY },
  { id: 'u_cp_5', propertyId: 'p_cedarpark', label: 'Cottage 5', bedrooms: 3, bathrooms: 2, sqft: 1240, tenant: 'Diana Cho', createdAt: NOW - 220 * DAY },
  // Mockingbird Manor
  { id: 'u_mm_104', propertyId: 'p_mockingbird', label: 'Unit 104', bedrooms: 1, bathrooms: 1, sqft: 580, tenant: 'Gabe Tran', createdAt: NOW - 175 * DAY },
  { id: 'u_mm_212', propertyId: 'p_mockingbird', label: 'Unit 212', bedrooms: 2, bathrooms: 1, sqft: 820, tenant: 'Maya Goldberg', createdAt: NOW - 175 * DAY },
  { id: 'u_mm_318', propertyId: 'p_mockingbird', label: 'Unit 318', bedrooms: 2, bathrooms: 2, sqft: 950, tenant: 'Ethan Briar', createdAt: NOW - 175 * DAY },
  // Travis Heights Bungalows
  { id: 'u_th_1', propertyId: 'p_travisheights', label: 'Bungalow 1', bedrooms: 2, bathrooms: 1, sqft: 1080, tenant: 'The Hollis Family', createdAt: NOW - 130 * DAY },
  { id: 'u_th_2', propertyId: 'p_travisheights', label: 'Bungalow 2', bedrooms: 3, bathrooms: 2, sqft: 1320, tenant: 'Iris Kowalski', createdAt: NOW - 130 * DAY },
  // Eastside Brownstones
  { id: 'u_es_a', propertyId: 'p_eastside', label: 'Brownstone A', bedrooms: 3, bathrooms: 2, sqft: 1480, tenant: 'The Adeyemi Family', createdAt: NOW - 105 * DAY },
  { id: 'u_es_b', propertyId: 'p_eastside', label: 'Brownstone B', bedrooms: 2, bathrooms: 2, sqft: 1180, tenant: 'Nico Marchetti', createdAt: NOW - 105 * DAY },
  // Mueller Mid-Rise
  { id: 'u_mu_502', propertyId: 'p_mueller', label: 'Apt 502', bedrooms: 1, bathrooms: 1, sqft: 690, tenant: 'Sage Kim', createdAt: NOW - 75 * DAY },
  { id: 'u_mu_708', propertyId: 'p_mueller', label: 'Apt 708', bedrooms: 2, bathrooms: 2, sqft: 1010, tenant: 'The Ortega-Hayes Household', createdAt: NOW - 75 * DAY },
  // Hillcrest Garden Apartments
  { id: 'u_hc_4', propertyId: 'p_hillcrest', label: 'Unit 4', bedrooms: 1, bathrooms: 1, sqft: 640, tenant: 'Bea Olufsen', createdAt: NOW - 60 * DAY },
  { id: 'u_hc_9', propertyId: 'p_hillcrest', label: 'Unit 9', bedrooms: 2, bathrooms: 1, sqft: 880, tenant: 'The Velasquez Family', createdAt: NOW - 60 * DAY },
  // Northgate Office Plaza
  { id: 'u_ng_100', propertyId: 'p_northgate', label: 'Suite 100', sqft: 2400, tenant: 'Ironwood Accounting', createdAt: NOW - 45 * DAY },
  { id: 'u_ng_205', propertyId: 'p_northgate', label: 'Suite 205', sqft: 1800, tenant: 'Ridgeline Therapy Group', createdAt: NOW - 45 * DAY },
  // Bouldin Creek Live-Work Lofts
  { id: 'u_bc_201', propertyId: 'p_bouldin', label: 'Loft 201', sqft: 1100, tenant: 'Studio Marais (design)', createdAt: NOW - 30 * DAY },
  { id: 'u_bc_303', propertyId: 'p_bouldin', label: 'Loft 303', sqft: 1280, tenant: 'Cardinal Coffee Roasters', createdAt: NOW - 30 * DAY },
];

const RES_CHECKLIST: Omit<InspectionItem, 'id' | 'status' | 'photos'>[] = [
  { category: 'Entry', label: 'Front door operates and locks securely' },
  { category: 'Entry', label: 'Smoke + CO detector functional, batteries fresh' },
  { category: 'Living Area', label: 'Walls, ceiling, baseboards in good repair' },
  { category: 'Living Area', label: 'Windows open, close, and lock' },
  { category: 'Living Area', label: 'HVAC vents clean, thermostat operable' },
  { category: 'Kitchen', label: 'Sink fixtures operate, no leaks under cabinet' },
  { category: 'Kitchen', label: 'Refrigerator + freezer cooling correctly' },
  { category: 'Kitchen', label: 'Stove burners + oven heat to set temperature' },
  { category: 'Kitchen', label: 'Garbage disposal operates without grinding' },
  { category: 'Bathroom', label: 'Toilet flushes, no running, no rocking' },
  { category: 'Bathroom', label: 'Shower/tub drains within 30s, no standing water' },
  { category: 'Bathroom', label: 'Exhaust fan operates' },
  { category: 'Bathroom', label: 'Caulking + grout intact, no mold visible' },
  { category: 'Bedroom', label: 'Closet doors operable, hardware intact' },
  { category: 'Bedroom', label: 'Outlets test live; no scorch marks' },
  { category: 'Exterior', label: 'No exterior water intrusion at windows or roof line' },
];

const COM_CHECKLIST: Omit<InspectionItem, 'id' | 'status' | 'photos'>[] = [
  { category: 'Loading Dock', label: 'Bay door operates, weather seal intact' },
  { category: 'Loading Dock', label: 'Dock leveler functional, safety chocks present' },
  { category: 'Floor', label: 'Concrete floor crack-free in main bay' },
  { category: 'Floor', label: 'Floor markings + safety lines visible' },
  { category: 'Electrical', label: 'Panel labeled, no exposed wiring' },
  { category: 'Electrical', label: 'Emergency lighting tests and holds 90s' },
  { category: 'Plumbing', label: 'Restroom fixtures operate, no leaks' },
  { category: 'HVAC', label: 'Rooftop unit serviced within 12 months' },
  { category: 'Safety', label: 'Fire extinguishers tagged within 12 months' },
  { category: 'Safety', label: 'Sprinkler heads clear, no obstructions within 18"' },
  { category: 'Exterior', label: 'Roof drains + gutters clear of debris' },
  { category: 'Exterior', label: 'Parking lot striping + ADA spaces compliant' },
];

function buildItems(prefix: string, kind: 'res' | 'com', failures: number[] = []): InspectionItem[] {
  const list = kind === 'res' ? RES_CHECKLIST : COM_CHECKLIST;
  return list.map((it, idx) => ({
    ...it,
    id: `${prefix}_i${idx}`,
    status: 'pending',
    photos: [],
    ...(failures.includes(idx)
      ? { status: 'fail' as const, severity: idx % 3 === 0 ? 'high' as const : 'medium' as const, notes: SAMPLE_NOTES[idx % SAMPLE_NOTES.length] }
      : {}),
  }));
}

const SAMPLE_NOTES = [
  'Visible water staining around fixture base; suspect slow leak.',
  'Caulk has separated from tile; moisture intrusion likely behind wall.',
  'Outlet reads 87V under load — wiring fault suspected, do not rely.',
  'Filter heavily clogged; airflow restricted at all vents.',
  'Hinge backed out of jamb, door does not latch fully.',
];

export const SEED_INSPECTIONS: Inspection[] = [
  {
    id: 'i_completed_oc2b',
    propertyId: 'p_oakcrest', propertyName: 'Oakcrest Apartments',
    unitId: 'u_oc_2b', unitLabel: 'Unit 2B',
    inspectorId: 'u_insp_1', inspectorName: 'Marco Reyes',
    status: 'completed',
    scheduledFor: NOW - 6 * DAY,
    startedAt: NOW - 6 * DAY,
    completedAt: NOW - 6 * DAY + 90 * 60 * 1000,
    items: buildItems('i1', 'res', [2, 5, 9]).map(it => ({ ...it, status: it.status === 'pending' ? 'pass' : it.status })),
    generalNotes: 'Tenant cooperative. Slow drain in master bath, called out under bathroom items.',
    aiSummary: 'Unit 2B at Oakcrest Apartments is in serviceable but flagged condition. Three items failed inspection: living-area wall damage near baseboard (medium), kitchen sink leak under cabinet (high), and master bath toilet rocking on flange (medium). The plumbing flags should be triaged together — sub-floor moisture risk if both are slow leaks. No life-safety concerns identified; smoke detector tested operational.',
    aiSummaryCachedAt: NOW - 6 * DAY,
    reportUrl: '#',
    createdAt: NOW - 7 * DAY,
  },
  {
    id: 'i_inprogress_law305',
    propertyId: 'p_lawson', propertyName: 'Lawson Lofts',
    unitId: 'u_law_305', unitLabel: 'Loft 305',
    inspectorId: 'u_insp_2', inspectorName: 'Priya Shah',
    status: 'in_progress',
    scheduledFor: NOW - 2 * 60 * 60 * 1000,
    startedAt: NOW - 90 * 60 * 1000,
    items: buildItems('i2', 'res', [10]).map((it, idx) => idx < 7 ? { ...it, status: it.status === 'pending' ? 'pass' : it.status } : it),
    generalNotes: '',
    createdAt: NOW - 1 * DAY,
  },
  {
    id: 'i_scheduled_rs_a1',
    propertyId: 'p_riverside', propertyName: 'Riverside Townhomes',
    unitId: 'u_rs_a1', unitLabel: 'Townhome A1',
    inspectorId: 'u_insp_1', inspectorName: 'Marco Reyes',
    status: 'scheduled',
    scheduledFor: NOW + 2 * DAY,
    items: buildItems('i3', 'res'),
    createdAt: NOW - 1 * DAY,
  },
  {
    id: 'i_scheduled_wh_a',
    propertyId: 'p_warehouse', propertyName: 'Westside Industrial Park',
    unitId: 'u_wh_a', unitLabel: 'Bay A',
    inspectorId: 'u_insp_2', inspectorName: 'Priya Shah',
    status: 'scheduled',
    scheduledFor: NOW + 4 * DAY,
    items: buildItems('i4', 'com'),
    createdAt: NOW - 1 * DAY,
  },
  {
    id: 'i_completed_oc4c',
    propertyId: 'p_oakcrest', propertyName: 'Oakcrest Apartments',
    unitId: 'u_oc_4c', unitLabel: 'Unit 4C',
    inspectorId: 'u_insp_2', inspectorName: 'Priya Shah',
    status: 'completed',
    scheduledFor: NOW - 14 * DAY,
    startedAt: NOW - 14 * DAY,
    completedAt: NOW - 14 * DAY + 75 * 60 * 1000,
    items: buildItems('i5', 'res', [13]).map(it => ({ ...it, status: it.status === 'pending' ? 'pass' : it.status })),
    generalNotes: 'Unit in excellent overall condition.',
    aiSummary: 'Unit 4C at Oakcrest Apartments is in strong overall condition with one minor finding: bedroom closet door hardware loose. No safety concerns. Recommend routine hardware tightening at next maintenance pass; no escalation warranted.',
    aiSummaryCachedAt: NOW - 14 * DAY,
    reportUrl: '#',
    createdAt: NOW - 15 * DAY,
  },
  // Cedar Park Cottages
  {
    id: 'i_scheduled_cp3',
    propertyId: 'p_cedarpark', propertyName: 'Cedar Park Cottages',
    unitId: 'u_cp_3', unitLabel: 'Cottage 3',
    inspectorId: 'u_insp_1', inspectorName: 'Marco Reyes',
    status: 'scheduled',
    scheduledFor: NOW + 3 * DAY,
    items: buildItems('i6', 'res'),
    createdAt: NOW - 2 * DAY,
  },
  // Mockingbird Manor
  {
    id: 'i_completed_mm104',
    propertyId: 'p_mockingbird', propertyName: 'Mockingbird Manor',
    unitId: 'u_mm_104', unitLabel: 'Unit 104',
    inspectorId: 'u_insp_2', inspectorName: 'Priya Shah',
    status: 'completed',
    scheduledFor: NOW - 18 * DAY,
    startedAt: NOW - 18 * DAY,
    completedAt: NOW - 18 * DAY + 70 * 60 * 1000,
    items: buildItems('i7', 'res', [3, 11]).map(it => ({ ...it, status: it.status === 'pending' ? 'pass' : it.status })),
    generalNotes: 'Window in living area sticking. Bath fan louder than spec.',
    aiSummary: 'Unit 104 at Mockingbird Manor is overall serviceable with two minor flags: living-area window difficult to open (medium) and bathroom exhaust fan operating but with bearing noise (medium). Neither is life-safety critical. Recommend bath fan replacement within 60 days; window track lubrication suffices for the casement.',
    aiSummaryCachedAt: NOW - 18 * DAY,
    reportUrl: '#',
    createdAt: NOW - 19 * DAY,
  },
  {
    id: 'i_scheduled_mm212',
    propertyId: 'p_mockingbird', propertyName: 'Mockingbird Manor',
    unitId: 'u_mm_212', unitLabel: 'Unit 212',
    inspectorId: 'u_insp_1', inspectorName: 'Marco Reyes',
    status: 'scheduled',
    scheduledFor: NOW + 5 * DAY,
    items: buildItems('i8', 'res'),
    createdAt: NOW - 1 * DAY,
  },
  // Travis Heights
  {
    id: 'i_inprogress_th1',
    propertyId: 'p_travisheights', propertyName: 'Travis Heights Bungalows',
    unitId: 'u_th_1', unitLabel: 'Bungalow 1',
    inspectorId: 'u_insp_1', inspectorName: 'Marco Reyes',
    status: 'in_progress',
    scheduledFor: NOW - 3 * 60 * 60 * 1000,
    startedAt: NOW - 2 * 60 * 60 * 1000,
    items: buildItems('i9', 'res', [14]).map((it, idx) => idx < 9 ? { ...it, status: it.status === 'pending' ? 'pass' : it.status } : it),
    generalNotes: 'Older property — checking outlets carefully.',
    createdAt: NOW - 1 * DAY,
  },
  // Eastside Brownstones
  {
    id: 'i_completed_es_a',
    propertyId: 'p_eastside', propertyName: 'Eastside Brownstones',
    unitId: 'u_es_a', unitLabel: 'Brownstone A',
    inspectorId: 'u_insp_2', inspectorName: 'Priya Shah',
    status: 'completed',
    scheduledFor: NOW - 9 * DAY,
    startedAt: NOW - 9 * DAY,
    completedAt: NOW - 9 * DAY + 95 * 60 * 1000,
    items: buildItems('i10', 'res', [6]).map(it => ({ ...it, status: it.status === 'pending' ? 'pass' : it.status })),
    generalNotes: 'Refrigerator running warm — flagged for service call.',
    aiSummary: 'Brownstone A at Eastside is in solid condition with one functional finding: kitchen refrigerator holding 44°F instead of target 38°F (medium). Door seal appears intact; suspect compressor or thermostat. Recommend appliance service before food-safety risk emerges. No structural or life-safety concerns.',
    aiSummaryCachedAt: NOW - 9 * DAY,
    reportUrl: '#',
    createdAt: NOW - 10 * DAY,
  },
  {
    id: 'i_scheduled_es_b',
    propertyId: 'p_eastside', propertyName: 'Eastside Brownstones',
    unitId: 'u_es_b', unitLabel: 'Brownstone B',
    inspectorId: 'u_insp_1', inspectorName: 'Marco Reyes',
    status: 'scheduled',
    scheduledFor: NOW + 6 * DAY,
    items: buildItems('i11', 'res'),
    createdAt: NOW - 2 * DAY,
  },
  // Mueller Mid-Rise
  {
    id: 'i_completed_mu502',
    propertyId: 'p_mueller', propertyName: 'Mueller Mid-Rise',
    unitId: 'u_mu_502', unitLabel: 'Apt 502',
    inspectorId: 'u_insp_2', inspectorName: 'Priya Shah',
    status: 'completed',
    scheduledFor: NOW - 4 * DAY,
    startedAt: NOW - 4 * DAY,
    completedAt: NOW - 4 * DAY + 65 * 60 * 1000,
    items: buildItems('i12', 'res').map(it => ({ ...it, status: it.status === 'pending' ? 'pass' : it.status })),
    generalNotes: 'New construction, pristine condition. No findings.',
    aiSummary: 'Apt 502 at Mueller Mid-Rise passed inspection with zero findings. Unit is in as-built condition. No maintenance recommended at this cycle.',
    aiSummaryCachedAt: NOW - 4 * DAY,
    reportUrl: '#',
    createdAt: NOW - 5 * DAY,
  },
  {
    id: 'i_scheduled_mu708',
    propertyId: 'p_mueller', propertyName: 'Mueller Mid-Rise',
    unitId: 'u_mu_708', unitLabel: 'Apt 708',
    inspectorId: 'u_insp_2', inspectorName: 'Priya Shah',
    status: 'scheduled',
    scheduledFor: NOW + 1 * DAY,
    items: buildItems('i13', 'res'),
    createdAt: NOW - 1 * DAY,
  },
  // Hillcrest Garden Apartments
  {
    id: 'i_completed_hc4',
    propertyId: 'p_hillcrest', propertyName: 'Hillcrest Garden Apartments',
    unitId: 'u_hc_4', unitLabel: 'Unit 4',
    inspectorId: 'u_insp_1', inspectorName: 'Marco Reyes',
    status: 'completed',
    scheduledFor: NOW - 22 * DAY,
    startedAt: NOW - 22 * DAY,
    completedAt: NOW - 22 * DAY + 80 * 60 * 1000,
    items: buildItems('i14', 'res', [4, 12]).map(it => ({ ...it, status: it.status === 'pending' ? 'pass' : it.status })),
    generalNotes: 'HVAC vents very dusty — filter likely overdue.',
    aiSummary: 'Unit 4 at Hillcrest is in serviceable condition with two findings: HVAC airflow restricted (high — filter heavily clogged, replace immediately) and bathroom caulk separation around tub (medium — moisture intrusion risk if not addressed). Other systems pass. Recommend filter replacement and re-caulk within 30 days.',
    aiSummaryCachedAt: NOW - 22 * DAY,
    reportUrl: '#',
    createdAt: NOW - 23 * DAY,
  },
  {
    id: 'i_inprogress_hc9',
    propertyId: 'p_hillcrest', propertyName: 'Hillcrest Garden Apartments',
    unitId: 'u_hc_9', unitLabel: 'Unit 9',
    inspectorId: 'u_insp_2', inspectorName: 'Priya Shah',
    status: 'in_progress',
    scheduledFor: NOW - 4 * 60 * 60 * 1000,
    startedAt: NOW - 3 * 60 * 60 * 1000,
    items: buildItems('i15', 'res').map((it, idx) => idx < 5 ? { ...it, status: it.status === 'pending' ? 'pass' : it.status } : it),
    generalNotes: '',
    createdAt: NOW - 1 * DAY,
  },
  // Northgate Office Plaza
  {
    id: 'i_scheduled_ng100',
    propertyId: 'p_northgate', propertyName: 'Northgate Office Plaza',
    unitId: 'u_ng_100', unitLabel: 'Suite 100',
    inspectorId: 'u_insp_2', inspectorName: 'Priya Shah',
    status: 'scheduled',
    scheduledFor: NOW + 7 * DAY,
    items: buildItems('i16', 'com'),
    createdAt: NOW - 1 * DAY,
  },
  // Bouldin Creek
  {
    id: 'i_completed_bc201',
    propertyId: 'p_bouldin', propertyName: 'Bouldin Creek Live-Work Lofts',
    unitId: 'u_bc_201', unitLabel: 'Loft 201',
    inspectorId: 'u_insp_1', inspectorName: 'Marco Reyes',
    status: 'completed',
    scheduledFor: NOW - 11 * DAY,
    startedAt: NOW - 11 * DAY,
    completedAt: NOW - 11 * DAY + 100 * 60 * 1000,
    items: buildItems('i17', 'com', [8]).map(it => ({ ...it, status: it.status === 'pending' ? 'pass' : it.status })),
    generalNotes: 'Tenant uses ground floor as design studio. Egress lighting needs check.',
    aiSummary: 'Loft 201 at Bouldin Creek passed inspection with one finding: fire extinguisher tag expired (medium — code-compliance issue, recharge or replace within 14 days). Egress lighting tested and held. No structural concerns. Schedule re-inspection of safety items at next cycle.',
    aiSummaryCachedAt: NOW - 11 * DAY,
    reportUrl: '#',
    createdAt: NOW - 12 * DAY,
  },
];

export const SEED_TICKETS: Ticket[] = [
  {
    id: 't_001',
    propertyId: 'p_oakcrest', propertyName: 'Oakcrest Apartments',
    unitId: 'u_oc_2b', unitLabel: 'Unit 2B',
    inspectionId: 'i_completed_oc2b', inspectionItemId: 'i1_i5',
    title: 'Sink leak under kitchen cabinet',
    description: 'Visible water staining around fixture base; suspect slow leak. Triage with bath toilet flange.',
    status: 'in_progress', priority: 'high',
    assigneeId: 'u_insp_1', assigneeName: 'Marco Reyes',
    photos: [],
    createdBy: 'u_insp_1',
    createdAt: NOW - 6 * DAY,
  },
  {
    id: 't_002',
    propertyId: 'p_oakcrest', propertyName: 'Oakcrest Apartments',
    unitId: 'u_oc_2b', unitLabel: 'Unit 2B',
    inspectionId: 'i_completed_oc2b', inspectionItemId: 'i1_i9',
    title: 'Master bath toilet rocks on flange',
    description: 'Toilet rocks 1/2" — wax ring likely compromised. Pull, reseat, replace ring.',
    status: 'open', priority: 'medium',
    photos: [],
    createdBy: 'u_insp_1',
    createdAt: NOW - 6 * DAY,
  },
  {
    id: 't_003',
    propertyId: 'p_oakcrest', propertyName: 'Oakcrest Apartments',
    unitId: 'u_oc_4c', unitLabel: 'Unit 4C',
    inspectionId: 'i_completed_oc4c', inspectionItemId: 'i5_i13',
    title: 'Closet door hardware loose in main bedroom',
    description: 'Hinge backed out of jamb, door does not latch fully.',
    status: 'resolved', priority: 'low',
    assigneeId: 'u_insp_2', assigneeName: 'Priya Shah',
    photos: [],
    createdBy: 'u_insp_2',
    createdAt: NOW - 14 * DAY,
    resolvedAt: NOW - 12 * DAY,
    resolutionNotes: 'Replaced hinge screws with longer #10s, door now seats and latches.',
  },
  {
    id: 't_004',
    propertyId: 'p_eastside', propertyName: 'Eastside Brownstones',
    unitId: 'u_es_a', unitLabel: 'Brownstone A',
    inspectionId: 'i_completed_es_a', inspectionItemId: 'i10_i6',
    title: 'Refrigerator holding 44°F (target 38°F)',
    description: 'Compressor or thermostat suspected. Door seal intact. Schedule appliance service before food-safety risk.',
    status: 'open', priority: 'medium',
    photos: [],
    createdBy: 'u_insp_2',
    createdAt: NOW - 9 * DAY,
  },
  {
    id: 't_005',
    propertyId: 'p_hillcrest', propertyName: 'Hillcrest Garden Apartments',
    unitId: 'u_hc_4', unitLabel: 'Unit 4',
    inspectionId: 'i_completed_hc4', inspectionItemId: 'i14_i4',
    title: 'HVAC filter heavily clogged — replace immediately',
    description: 'Airflow restricted at all vents. Replace filter and inspect coils for buildup.',
    status: 'in_progress', priority: 'high',
    assigneeId: 'u_insp_1', assigneeName: 'Marco Reyes',
    photos: [],
    createdBy: 'u_insp_1',
    createdAt: NOW - 22 * DAY,
  },
  {
    id: 't_006',
    propertyId: 'p_hillcrest', propertyName: 'Hillcrest Garden Apartments',
    unitId: 'u_hc_4', unitLabel: 'Unit 4',
    inspectionId: 'i_completed_hc4', inspectionItemId: 'i14_i12',
    title: 'Bathroom tub caulk separation',
    description: 'Caulk has separated from tile; moisture intrusion likely behind wall.',
    status: 'open', priority: 'medium',
    photos: [],
    createdBy: 'u_insp_1',
    createdAt: NOW - 22 * DAY,
  },
  {
    id: 't_007',
    propertyId: 'p_bouldin', propertyName: 'Bouldin Creek Live-Work Lofts',
    unitId: 'u_bc_201', unitLabel: 'Loft 201',
    inspectionId: 'i_completed_bc201', inspectionItemId: 'i17_i8',
    title: 'Fire extinguisher tag expired',
    description: 'Code-compliance issue. Recharge or replace within 14 days.',
    status: 'resolved', priority: 'medium',
    assigneeId: 'u_insp_1', assigneeName: 'Marco Reyes',
    photos: [],
    createdBy: 'u_insp_1',
    createdAt: NOW - 11 * DAY,
    resolvedAt: NOW - 8 * DAY,
    resolutionNotes: 'Replaced with new ABC dry-chemical extinguisher; tag dated and mounted.',
  },
  {
    id: 't_008',
    propertyId: 'p_mockingbird', propertyName: 'Mockingbird Manor',
    unitId: 'u_mm_104', unitLabel: 'Unit 104',
    inspectionId: 'i_completed_mm104', inspectionItemId: 'i7_i11',
    title: 'Bathroom exhaust fan bearing noise',
    description: 'Fan operates but bearing is failing — replace within 60 days before motor seizes.',
    status: 'open', priority: 'medium',
    photos: [],
    createdBy: 'u_insp_2',
    createdAt: NOW - 18 * DAY,
  },
];
